# Generated by Django 2.2.3 on 2019-07-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Description',
            field=models.TextField(default='No Description Yet'),
        ),
    ]
